Feature/Implementar ActivityCellView
devpass-tech/challenge-viewcode-finance pull request #27
Opened 2022-04-14 18:09 UTC by hayato-eth

## Description
A ActivityCellView é um componente de interface que mostra as informações de uma atividade na conta bancária de um usuário.

## Technical Description

- [x]  Implementar a interface em um arquivo separado com o nome ActivityCellView.swift
- [x]  O componente deve mostrar uma imagem, o nome e valor da compra e horário em que foi realizada
- [x]  Utilizar método activityDetails (arquivo String+Extensions.swift) para configurar valor e horário da atividade
- [x]  A interface deve ser implementada conforme o anexo
- [x]  Implementar Teste de Snapshot para componente

## Snapshots

### Implementation
![Screen Shot 2022-04-14 at 15 06 50](https://user-images.githubusercontent.com/43426385/163450808-3f8c6a7e-389b-4407-9db9-23fd532f11d6.png)

### Tests
![testDarkMode 1](https://user-images.githubusercontent.com/43426385/163450905-bbe33c35-216e-4c85-9fb3-855b2a866ca9.png)
![testDefaultState 1](https://user-images.githubusercontent.com/43426385/163450912-e4d317ef-8a42-480d-85b4-e20c1b770a02.png)

2022-04-15 00:20 UTC, LeticiaSpeda commented on solutions/devsprint-devpoli-1/ActivityCellView.swift
> +        stack.alignment = .center
Aconselho voce a colocar o eixo que voce quer na sua stack se é vertical ou horizontal (axis = .vertical)

2022-04-15 00:23 UTC, LeticiaSpeda commented on solutions/devsprint-devpoli-1/ActivityCellView.swift
> +        return label
Aconselho a sempre colocar a cor da sua fonte, pois se voce alterar o seu device para dark mode pode ocorrer nao mostrar seu texto

2022-04-15 00:26 UTC, LeticiaSpeda commented on solutions/devsprint-devpoli-1/ActivityCellView.swift
> +    lazy var activityDescriptionLabel: UILabel = {
Aconselho voce colocar pelo menos private(set) para ser visivel fora classe mais alteravel so dentro dela

2022-04-15 13:45 UTC, ArthurNvs commented on solutions/devsprint-devpoli-1/ActivityCellView.swift
> +    func setupActivityCategoryIcon(activityName: String) {
Acredito que aqui seja possível criar um método para evitar a repetição do código no seu Switch, 
algo assim:

private func setActivity(image: String, color: UIColor) {
    activityCategoryIcon.image =  UIImage(named: image)
    activityCategoryIcon.tintColor = color
}

O que acha?

2022-04-15 17:25 UTC, hayato-eth commented on solutions/devsprint-devpoli-1/ActivityCellView.swift
> +        stack.alignment = .center
Vou fazer essa alteração, muito obrigado.

2022-04-15 17:28 UTC, hayato-eth commented on solutions/devsprint-devpoli-1/ActivityCellView.swift
> +        return label
Eu tenho uma dúvida no dark mode.
No caso eu colocando uma fonte na cor ```.systemBlack```, a versão dark mode dela vai ser a ```.systemWhite```?

2022-04-15 17:28 UTC, hayato-eth commented on solutions/devsprint-devpoli-1/ActivityCellView.swift
> +    lazy var activityDescriptionLabel: UILabel = {
Vou fazer a alteração, muito obrigado

2022-04-15 21:12 UTC, policante commented on solutions/devsprint-devpoli-1/ActivityCellView.swift
> +        return label
Quando você usa o `system`, ele pega o de acordo com o modo do device. Então ele não muda para o `.systemWhite`, mas ele vai ficar branco.
Sempre utilize o .white ou .black

2022-04-15 21:57 UTC, policante requested changes

2022-04-15 21:57 UTC, policante commented on solutions/devsprint-devpoli-1/FinanceApp/Screens/Home/HomeView.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: ActivityCellView.identifier) as! ActivityCellView
Evite utilizar `!`, pois caso a informação for nula, o seu app pode crashar.

2022-04-15 21:57 UTC, policante commented on solutions/devsprint-devpoli-1/FinanceAppTests/Components/ActivityCellViewTests.swift
> +        let container = sut!
Evite utilizar `!`, pois caso a informação for nula, o seu app pode crashar.

2022-04-15 21:57 UTC, policante commented on solutions/devsprint-devpoli-1/FinanceAppTests/Components/ActivityCellViewTests.swift
> +        let container = sut!
Evite utilizar `!`, pois caso a informação for nula, o seu app pode crashar.

2022-04-15 21:57 UTC, policante commented on solutions/devsprint-devpoli-1/FinanceAppTests/Components/ActivityCellViewTests.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell", for: indexPath) as! Cell
Evite utilizar `!`, pois caso a informação for nula, o seu app pode crashar.

2022-04-19 21:25 UTC, hayato-eth reviewed
Alterações finalizadas

2022-04-19 23:24 UTC, policante requested changes

2022-04-19 23:24 UTC, policante commented on solutions/devsprint-devpoli-1/FinanceApp/Screens/Home/HomeView.swift
> +        ) as? ActivityCellView ?? ActivityCellView(style: UITableViewCell.CellStyle.default, reuseIdentifier: ActivityCellView.identifier)
Nessas situações, você pode realizar o `guard` da cell fazendo o cast para `ActivityCellView`. Caso não der a validação, você retorna a UITableViewCell padrão.

Não é pra entrar nesse cenario, mas você retorna uma cell em branco e o app "oculta" a informação

2022-04-19 23:24 UTC, policante commented on solutions/devsprint-devpoli-1/FinanceAppTests/Components/ActivityCellViewTests.swift
> +class TableViewCellSnapshotContainer<Cell: UITableViewCell>: UIView, UITableViewDataSource, UITableViewDelegate {
Não é necessário criar essa class

2022-04-22 20:22 UTC, policante approved these changes

2022-04-22 20:22 UTC, merged