adding bar button with profile image
devpass-tech/challenge-viewcode-finance pull request #37
Opened 2022-05-17 17:09 UTC by marcioa1

CREating a bar button for profile

2022-05-18 09:49 UTC, ananogal requested changes

2022-05-18 09:49 UTC, ananogal commented on solutions/devsprint-ana-nogal-2/FinanceApp/Screens/Home/HomeView.swift
> +
Please verify what type of spaces you are using in your Xcode so we are all aligned and avoid this kind of change.
You Can change it in `Xcode-> Preferences...-> Text Editing`

2022-05-18 09:49 UTC, ananogal commented on solutions/devsprint-ana-nogal-2/FinanceApp/Screens/Home/HomeView.swift
> +    private (set) lazy var profileButton: UIBarButtonItem = {
Loved it: you are using`private (set)`; this shows you are careful when exposing your properties. But is `profileButton` a `UI` element of `HomeView`? or is it a UI element of `HomeViewController`? Where is it used?

2022-05-18 09:49 UTC, ananogal commented on solutions/devsprint-ana-nogal-2/FinanceApp/Screens/Home/HomeViewController.swift
> +        navigationItem.rightBarButtonItem = homeView.profileButton
This is giving you a clue to my previous question 😄

2022-05-18 09:49 UTC, ananogal commented on solutions/devsprint-ana-nogal-2/FinanceApp/Screens/Home/HomeViewController.swift
> +        navigationItem.rightBarButtonItem = homeView.profileButton
This is giving you a clue to my previous question 😄

2022-05-18 09:49 UTC, ananogal commented on solutions/devsprint-ana-nogal-2/FinanceAppTests/Screens/Home/HomeViewTests.swift
> +    func test_navigationBar_mustHaveRightButtons() {
The name of the test does not reflect what you are testing: You are saying you should have `RightButtons`, but in the test, you are verifying if the `HomeView` is not `nil`. You have three choices:

1. Change the name of the test
2. Change what the test is testing, 
3. Delete the test if it is not bringing any value anymore.

2022-05-18 09:49 UTC, ananogal commented on solutions/devsprint-ana-nogal-2/FinanceAppTests/Screens/Home/HomeViewTests.swift
> +    func test_navigationBar_mustHaveRightButtons() {
The name of the test does not reflect what you are testing: You are saying you should have RighjtButtons, but in the test, you are testing if the `HomeView` is not `nil`. Change the name of the test, or change what the test is testing, or delete the east if is not bringing any value to you

2022-05-18 09:49 UTC, ananogal commented on solutions/devsprint-ana-nogal-2/FinanceAppTests/Screens/Home/HomeViewTests.swift
> +class HomeViewTests: XCTestCase {
These tests are UnitTests, not Snapshot tests which is what was asked for in the task. You can maintain the Unit test, nothing wrong with them, but please add Snapshot tests.

2022-05-18 09:49 UTC, ananogal commented on solutions/devsprint-ana-nogal-2/FinanceAppTests/Screens/Home/HomeViewTests.swift
> +class HomeViewTests: XCTestCase {
These tests are UnitTests, not Snapshot tests which is what was asked for in the task. You can maintain the Unit test, nothing wrong with them, but please add Snapshot tests.

2022-05-18 10:57 UTC, marcioa1 commented on solutions/devsprint-ana-nogal-2/FinanceApp/Screens/Home/HomeView.swift
> +    private (set) lazy var profileButton: UIBarButtonItem = {
It is used in HomeViewController but HomView is not where the view elements are created?

2022-05-18 10:58 UTC, marcioa1 commented on solutions/devsprint-ana-nogal-2/FinanceApp/Screens/Home/HomeViewController.swift
> +        navigationItem.rightBarButtonItem = homeView.profileButton
yes, but HomeView is not the one responsible to create the ui elements?

2022-05-18 10:58 UTC, marcioa1 commented on solutions/devsprint-ana-nogal-2/FinanceAppTests/Screens/Home/HomeViewTests.swift
> +    func test_navigationBar_mustHaveRightButtons() {
Totally agree with you.

2022-05-18 10:59 UTC, marcioa1 commented on solutions/devsprint-ana-nogal-2/FinanceAppTests/Screens/Home/HomeViewTests.swift
> +class HomeViewTests: XCTestCase {
Ok

2022-05-18 14:04 UTC, ananogal commented on solutions/devsprint-ana-nogal-2/FinanceApp/Screens/Home/HomeViewController.swift
> +        navigationItem.rightBarButtonItem = homeView.profileButton
`HomeView` is responsible for creating the UI elements that it shows... The `ViewController` is the one that owns the `NavigationItem`/`NavigationBar` so it should be its responsibility to create buttons to set it. So much so you had to expose this button to be able to use it... this alone should tell you that you are using it outside `HomeView`... So should `HomeView` be responsible for the creation of something that it's not going to use?

2022-05-18 14:15 UTC, marcioa1 commented on solutions/devsprint-ana-nogal-2/FinanceApp/Screens/Home/HomeViewController.swift
> +        navigationItem.rightBarButtonItem = homeView.profileButton
I exposed the button ( private (set) ) to be used in the Unit Test ( that I didn't write it very well ). I was in doubt related to this questions. Is the button part of the view that the view controller will display? The test was bad written because I really don't know if the button is part of HomeView or HomeViewController ( of course every element is part of HomeViewController, like the tableView ). I can create the button ( a view element ) inside ViewController to see how it seems.

2022-05-23 19:16 UTC, marcioa1 commented on solutions/devsprint-ana-nogal-2/FinanceAppTests/Screens/Home/HomeViewTests.swift
> +    func test_navigationBar_mustHaveRightButtons() {
I deleted the test. I had problems with my project.pbxproj and it seems ester to solve it deleting the test

2022-06-07 18:51 UTC, closed without merging